feat: deploy implementation contracts for v1_2_1
liquid-collective/liquid-collective-protocol pull request #293
Opened 2024-09-11 17:14 UTC by koderholic

## Description

Changes included:
- updated deploy scripts to for v1_2_1 implementation deployment, and proxy upgrade.

## Notice

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/liquid-collective/liquid-collective-protocol/pulls) for the same update/change?
- [x] Have you assigned this PR to yourself?
- [x] Have you added at least 1 reviewer?
- [ ] Have you updated the official documentation?
- [x] Have you added sufficient documentation in your code?
- [ ] Have you added relevant tests to the official test suite?

## Pull Request Type

- [ ] 💫 New Feature (Breaking Change)
- [x] 💫 New Feature (Non-breaking Change)
- [ ] 🛠️ Bug fix (Non-breaking Change: Fixes an issue)
- [ ] 🕹️ Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)

## Breaking changes (if applicable)

## Testing

- [x] Have you tested this code with the official test suite?
- [x] Have you tested this code manually?

2024-09-16 12:37 UTC, jdiuwe submitted a review, later dismissed

2024-09-17 09:11 UTC, iamsahu requested changes
The scripts look good. Just a small change to make things easier in future upgrades.

2024-09-17 09:11 UTC, iamsahu commented on deploy/devHolesky/08_deployment_v1_2_1.ts
> +  const allowlistDeployment = await deployments.deploy("AllowlistV1_Implementation_1_2_1", {
We should introduce a variable for capturing the version number and then append the variable everywhere so in the future it becomes relatively easy to change the version & do a redeployment. We can follow the same pattern in the upgrade transaction script.

2024-09-17 09:15 UTC, koderholic commented on deploy/devHolesky/08_deployment_v1_2_1.ts
> +  const allowlistDeployment = await deployments.deploy("AllowlistV1_Implementation_1_2_1", {
Ok, so we use the same script for future deployments, just change of version. Ok, good.

2024-09-17 12:08 UTC, iamsahu approved these changes
LGTM!

2024-09-17 12:53 UTC, juliaaschmidt approved these changes
LGTM

2024-09-17 12:55 UTC, merged