Feat: RedeemManager Migration - Assumes  initiator equals recipient
liquid-collective/liquid-collective-protocol pull request #299
Opened 2024-09-30 17:38 UTC by koderholic

## Description
The current redeemManager migration for v1.2.1 upgrade requires an array of external provided addresses to be set for the initiator field of exiting redeemRequests without initiator. This could potentially introduce a margin for error, due to getting off-chain data into the protocol.

This PR creates a method of migrating which DOES NOT require any external data to be passed into the migration. 

## Notice

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/liquid-collective/liquid-collective-protocol/pulls) for the same update/change?
- [x] Have you assigned this PR to yourself?
- [x] Have you added at least 1 reviewer?
- [ ] Have you updated the official documentation?
- [x] Have you added sufficient documentation in your code?
- [x] Have you added relevant tests to the official test suite?

## Pull Request Type

- [ ] 💫 New Feature (Breaking Change)
- [x] 💫 New Feature (Non-breaking Change)
- [ ] 🛠️ Bug fix (Non-breaking Change: Fixes an issue)
- [ ] 🕹️ Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)

## Testing

- [ ] Have you tested this code with the official test suite?
- [x] Have you tested this code manually?

2024-10-01 09:09 UTC, iamsahu requested changes
Looks good, just a minor comment addition & getting the code coverage up.

2024-10-01 09:09 UTC, iamsahu commented on contracts/test/RedeemManager.1.t.sol
>          for (uint256 i = 0; i < 30; i++) {
Can we please add a comment explaining the number 30 here & 60 further down.

2024-10-01 09:15 UTC, koderholic commented on contracts/test/RedeemManager.1.t.sol
>          for (uint256 i = 0; i < 30; i++) {
Sure! I can add that, there's no significance behind the numbers though, it's a random choice.

2024-10-01 16:52 UTC, iamsahu submitted a review, later dismissed
🚀

2024-10-03 08:08 UTC, ATMackay approved these changes

2024-10-07 11:02 UTC, juliaaschmidt approved these changes
🚀 🚀

2024-10-10 11:49 UTC, mischat approved these changes
LGTM

2024-10-10 11:49 UTC, merged